url: ''
baseurl: ''
title: 'Mini Aussiedoodle'

plugins:
  - jekyll-postcss
  - jekyll-seo-tag

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - package-lock.json

collections:
  pages:
    output: true
    permalink: /:name

timezone: America/New_York

compress_html:
  blanklines: true