source 'https://rubygems.org'

gem 'base64'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
gem 'dotenv'
gem 'jekyll'
gem 'webrick'
gem 'jekyll-postcss'
gem 'jekyll-dotenv'
gem 'airtable'
gem 'activesupport'
gem 'jekyll-seo-tag'