require 'dotenv/load'
require 'airtable'
require 'active_support/all'
require 'yaml'
require 'fileutils'

module Jekyll
  class GenerateData < Generator
    safe true
    priority :highest

    def generate(site)
      airtable = Airtable::Client.new(ENV['AIRTABLE_ACCESS_TOKEN'])
      tables = ["Pages", "Posts"]

      tables.each do |table_name|
        table = airtable.table(ENV['AIRTABLE_BASE_ID'], table_name)
        records = table.records

        unless records.empty?
          # Write data to _data directory
          File.open(File.join(site.source, "_data/#{table_name.downcase}.yml"), 'w') do |file|
            data = records.map(&:attributes)
            warning = "# Do not edit this file manually \n"

            file.write(warning + data.to_yaml)
          end


        else
          puts "Skipping #{table_name} as it came back with no records..."
        end
      end
    end
  end
end