require 'dotenv/load'
require 'airtable'
require 'active_support/all'
require 'yaml'
require 'fileutils'

airtable = Airtable::Client.new(ENV['AIRTABLE_ACCESS_TOKEN'])
tables = ["Pages", "Posts"]

tables.each do |table_name|
  table = airtable.table(ENV['AIRTABLE_BASE_ID'], table_name)
  records = table.records

  unless records.empty?
    File.open("_data/#{table_name.downcase}.yml", 'w') do |file|
      data = records.map(&:attributes)
      warning = "# Do not edit this file manually \n"

      file.write(warning, data.to_yaml)
    end
    # Create files in _pages collection for "Pages" table
    if table_name == "Pages"
      records.each do |record|
        page_name = record['name'].parameterize
        page_title = record['name']
        file_path = "_pages/#{page_name}.md"

        content = <<-HEREDOC
---
layout: default
title: "#{page_title}"
---

{% assign page = site.data.pages | where: "name", "#{page_title}" | first %}

<section class="py-12">
  <article class="prose prose-img:rounded-xl prose-a:text-blue-400 prose-a:border-b-2 prose-a:border-blue-200 hover:prose-a:border-blue-400 prose-a:no-underline prose-h1:text-5xl w-full prose-h2:text-4xl prose-h3:text-3xl prose-h4:text-2xl prose-h5:text-xl prose-h6:text-lg prose-p:text-lg prose-ul:text-lg prose-ol:text-lg prose-blockquote:text-lg prose-img:shadow-xl prose-p:text-storm-dust-700 prose-headings:font-serif prose-headings:text-storm-dust-700 active:prose-a:border-b-4 prose-ul:text-storm-dust-700 prose-li:text-storm-dust-700 prose-strong:text-storm-dust-700 prose-li:marker:text-storm-dust-700">
    {{ page.body | markdownify }}
  </article>
</section>
        HEREDOC

        FileUtils.mkdir_p(File.dirname(file_path))
        File.open(file_path, 'w') { |file| file.write(content) }
      end
    end
  else
    puts "Skipping #{table_name} as it came back with no records..."
  end
end
